<!DOCTYPE html>

    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>README</title>
    </head>

    <body>
        <h1>Data Structures and Algorithms</h1>
        <h2>Huffman Compression</h2>
        <h2>Author: Ben Donovan</h2>

        <h2>Instructions:</h2>
        <ol>
            <li>Make sure Java is installed on your computer and in your PATH ( If on MacOS or Linux make sure it is in your .bashrc )</li>
            <li>cd into the src/compiled folder and then run "java App"</li>
            <li>Follow the instructions on screen to get started</li>
        </ol>

        <h2>Important Information</h2>
        <ul>
            <li>The tree generated by the Huffman Coding is kept separate from the encoded file. This is by design as it allows for files to be encoding using the Huffman tree generated for another file. WHEN YOU GO TO DECODE THE FILE THE CORRECT 'tree.txt' MUST BE IN THE SAME DIRECTORY AS THE FILE YOU ARE TRYING TO DECODE. If it is not the program will not decode the file properly.</li>
        </ul>

        <h2>Important Links:</h2>
        <ul>
            <li><a href="http://www.gutenberg.org/cache/epub/2267/pg2267.txt" >Othello English</a></li>
            <li><a href="https://www.gutenberg.org/files/18179/18179-8.txt" >Othello French</a></li>
            <li><a href="https://www.gutenberg.org/files/28526/28526-8.txt" >Othello Portuguese</a></li>

            <li><a href="http://www.gutenberg.org/cache/epub/2265/pg2265.txt" >Hamlet English</a></li>
            <li><a href="http://www.gutenberg.org/cache/epub/15032/pg15032.txt" >Hamlet French</a></li>
            <li><a href="http://www.gutenberg.org/cache/epub/25667/pg25667.txt" >Hamlet Portuguese</a></li>

            <li><a href="http://pizzachili.dcc.uchile.cl/repcorpus/artificial/fib41.7z" >Corpus Repetitive Dataset ( Artificial )</a></li>
            <li><a href="http://pizzachili.dcc.uchile.cl/repcorpus/pseudo-real/dblp.xml.00001.1.7z" >Corpus Repetitive Dataset ( Pseudo Real )</a></li>
            <li><a href="http://pizzachili.dcc.uchile.cl/repcorpus/real/world_leaders.7z" >Corpus Repetitive Dataset ( Real )</a></li>
        </ul>
    </body>

</html>